### ISSUE TITLE
NullPointerException when using willThrow with mock Exception

### ISSUE THREAD

**Issue by maciejmikosik** [testory/testory#90]
```
Object mock = mock(Object.class);
given(willThrow(mock(RuntimeException.class)), mock).toString();
mock.toString();
```

Exception in thread "main" java.lang.NullPointerException
    at org.testory.Testory$11.handle(Testory.java:307)
    at org.testory.Testory$4.handle(Testory.java:219)
    at org.testory.Testory$5.handle(Testory.java:230)
    at org.testory.proxy.Proxies$4.handle(Proxies.java:154)
    at org.testory.proxy.Proxies$3.intercept(Proxies.java:144)
    at org.testory.proxy.Proxies$ProxiableObject$$$EnhancerByCGLIB$$104ca767.toString(<generated>)
    at Main.main(Main.java:9)

**Comment by maciejmikosik** [comment]
stubbed `fillInStackTrace` to return same `this`
