### ISSUE TITLE
java.lang.Error when thenThrown failed

### ISSUE THREAD

**Issue by maciejmikosik** [testory/testory#93]
`java.lang.Error` is thrown when `thenThrown` tries to manipulate stack trace

```
java.lang.Error
	at org.testory.TestoryAssertionError.callerTrace(TestoryAssertionError.java:32)
	at org.testory.TestoryAssertionError.assertionError(TestoryAssertionError.java:16)
	at com.mikosik.testing.TestoryTest.thenThrown(TestoryTest.java:639)
	at com.mikosik.common.thread.pipe.TestBlockingPipe.detects_death_of_reader(TestBlockingPipe.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by maciejmikosik** [comment]
This happens when i invoke `TestoryAssertionError.assertionError` from class other than `Testory` or `Proxies`

**Comment by maciejmikosik** [comment]
Stack trace manipulation was disabled.
